name: go
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch::pytorch>=2.0.0
  - pytorch::pytorch-cuda=12.1
  - pytorch::torchvision
  - omegaconf
  - torchmetrics>=0.10.0
  - fvcore
  - iopath
  - torchinfo
  - cython
  - scipy>=1.10.0
  - kiwisolver
  - matplotlib>=3.7.0
  - numpy>=1.23.0,<2.0
  - vispy
  - einops
  - distinctipy
  - trimesh
  - pip
  - pip:
      - cython>=3.0.0
      - faiss-gpu
      - ultralytics==8.0.135
      - git+https://github.com/facebookincubator/submitit
      - kornia>=0.7.0
      - pypng
      - glumpy
      - pycocotools
      - scikit-learn>=1.3.0
      - scikit-image>=0.20.0
      - imageio
      - pyopengl
      - pyglet>=2.0.0
      - pytz
      - pyrender
      - webdataset
      - git+https://github.com/facebookresearch/hand_tracking_toolkit
      - opencv-python<4.10.0
      - pytorch-lightning>=1.8.0,<2.0.0
      - hydra-colorlog
      - hydra-core>=1.3.0
      - huggingface-hub
